function getNhlTeamLogo(abbrev: string): string {
  return `https://assets.nhle.com/logos/nhl/svg/${abbrev}_light.svg`;
}

export const NHL_TEAMS = [
  { abbrev: 'AUTO', name: 'Auto (follow schedule)' },
  { abbrev: 'ANA', name: 'Anaheim Ducks', logo: getNhlTeamLogo('ANA') },
  { abbrev: 'BOS', name: 'Boston Bruins', logo: getNhlTeamLogo('BOS') },
  { abbrev: 'BUF', name: 'Buffalo Sabres', logo: getNhlTeamLogo('BUF') },
  { abbrev: 'CAR', name: 'Carolina Hurricanes', logo: getNhlTeamLogo('CAR') },
  { abbrev: 'CBJ', name: 'Columbus Blue Jackets', logo: getNhlTeamLogo('CBJ') },
  { abbrev: 'CGY', name: 'Calgary Flames', logo: getNhlTeamLogo('CGY') },
  { abbrev: 'CHI', name: 'Chicago Blackhawks', logo: getNhlTeamLogo('CHI') },
  { abbrev: 'COL', name: 'Colorado Avalanche', logo: getNhlTeamLogo('COL') },
  { abbrev: 'DAL', name: 'Dallas Stars', logo: getNhlTeamLogo('DAL') },
  { abbrev: 'DET', name: 'Detroit Red Wings', logo: getNhlTeamLogo('DET') },
  { abbrev: 'EDM', name: 'Edmonton Oilers', logo: getNhlTeamLogo('EDM') },
  { abbrev: 'FLA', name: 'Florida Panthers', logo: getNhlTeamLogo('FLA') },
  { abbrev: 'LAK', name: 'Los Angeles Kings', logo: getNhlTeamLogo('LAK') },
  { abbrev: 'MIN', name: 'Minnesota Wild', logo: getNhlTeamLogo('MIN') },
  { abbrev: 'MTL', name: 'Montreal Canadiens', logo: getNhlTeamLogo('MTL') },
  { abbrev: 'NSH', name: 'Nashville Predators', logo: getNhlTeamLogo('NSH') },
  { abbrev: 'NJD', name: 'New Jersey Devils', logo: getNhlTeamLogo('NJD') },
  { abbrev: 'NYI', name: 'New York Islanders', logo: getNhlTeamLogo('NYI') },
  { abbrev: 'NYR', name: 'New York Rangers', logo: getNhlTeamLogo('NYR') },
  { abbrev: 'OTT', name: 'Ottawa Senators', logo: getNhlTeamLogo('OTT') },
  { abbrev: 'PHI', name: 'Philadelphia Flyers', logo: getNhlTeamLogo('PHI') },
  { abbrev: 'PIT', name: 'Pittsburgh Penguins', logo: getNhlTeamLogo('PIT') },
  { abbrev: 'SEA', name: 'Seattle Kraken', logo: getNhlTeamLogo('SEA') },
  { abbrev: 'SJS', name: 'San Jose Sharks', logo: getNhlTeamLogo('SJS') },
  { abbrev: 'STL', name: 'St. Louis Blues', logo: getNhlTeamLogo('STL') },
  { abbrev: 'TBL', name: 'Tampa Bay Lightning', logo: getNhlTeamLogo('TBL') },
  { abbrev: 'TOR', name: 'Toronto Maple Leafs', logo: getNhlTeamLogo('TOR') },
  { abbrev: 'UTA', name: 'Utah Mammoth', logo: getNhlTeamLogo('UTA') },
  { abbrev: 'VAN', name: 'Vancouver Canucks', logo: getNhlTeamLogo('VAN') },
  { abbrev: 'VGK', name: 'Vegas Golden Knights', logo: getNhlTeamLogo('VGK') },
  { abbrev: 'WPG', name: 'Winnipeg Jets', logo: getNhlTeamLogo('WPG') },
  { abbrev: 'WSH', name: 'Washington Capitals', logo: getNhlTeamLogo('WSH') },
] as const;

